---
- hosts: localhost
  connection: local
  become: true
  pre_tasks:
    - name: Update Package Cache
      tags: always
      apt: update_cache=yes
      changed_when: False
  
  tasks:
    # Install Flatpaks
    -include_tasks: ./software/flatpaks.yml