---
- hosts: localhost
  connection: local
  become: true
  pre_tasks:
    - name: Update Package Cache
      tags: always
      apt: update_cache=yes
      changed_when: False
  
  tasks:
    # Copy Files
    - include_tasks: ./files/files.yml

    # Configure Desktop
    - include_tasks: ./configure_desktop.yml

    # Install Flatpaks
    - include_tasks: ./software/flatpaks.yml